### PR TITLE
Fix multiple bugs

### LINKED ISSUE #132: Feature flaw for addleave command
Adding leave with invalid paramters for start date and end date does not show any error to the user side.

Example: `addleave id/1 sd/01012022 ed/02012022` does not prompt user of invalid input format

### PR DESCRIPTION
**Pull request by prit3010**
Fixes #132 #137 #134

### CODE REVIEW

File: src/main/java/coydir/logic/parser/FindCommandParser.java [hunk 1]
```diff
@@ -35,14 +37,22 @@ public FindCommand parse(String args) throws ParseException {
...
+            if (!Position.isValidPosition(keywordPosition)) {
+                throw new ParseException(Position.MESSAGE_CONSTRAINTS);
+            }
         }
         if (argMultimap.getValue(PREFIX_DEPARTMENT).isPresent()) {
             keywordDepartment = ParserUtil.parseKeyword(argMultimap.getValue(PREFIX_DEPARTMENT).get());
         }
 
+
+
```
Comment (chao890) [inline src/main/java/coydir/logic/parser/FindCommandParser.java:55]: Can remove this lines ?

File: src/main/java/coydir/logic/parser/ParserUtil.java [hunk 2]
```diff
@@ -25,7 +25,7 @@
  */
 public class ParserUtil {
 
-    public static final String MESSAGE_INVALID_INDEX = "Index is not a non-zero unsigned integer.";
+    public static final String MESSAGE_INVALID_INDEX = "Number should be non-zero positive integer.";
```
Comment (chao890) [inline src/main/java/coydir/logic/parser/ParserUtil.java:28]: Maybe add a "a" after "be" ?

**Review by chao890 — CHANGES_REQUESTED** [review]

**Review by chao890 — APPROVED** [review]
LGTM
