### PR TITLE
Bug fix

### LINKED ISSUE #93: Bug found
While I was playing around with Coydir, I suddenly ran into this error.

Screenshot 2022-10-17 at 11 45 24 PM 

Error is as such:
Screenshot 2022-10-17 at 11 47 51 PM

Upon backtracking, I found where this issue comes from. Once I add a input with no fields other than name and position, I get the error when I try start it up

Screenshot 2022-10-17 at 11 49 44 PM

Seems to be an issue with the parsing of the N/A fields from the `database.json`

Please advise

### PR DESCRIPTION
**Pull request by prit3010**
Fixes #93 

Instead of looking for null, JsonAdaptedPerson looks for N/A and initialises it to be empty when creating the Person Class

### CODE REVIEW

File: src/main/java/coydir/storage/JsonAdaptedPerson.java [hunk 1]
```diff
@@ -46,11 +46,12 @@ class JsonAdaptedPerson {
      */
     @JsonCreator
     public JsonAdaptedPerson(@JsonProperty("name") String name, @JsonProperty("employeeId") String employeeId,
-            @JsonProperty("phone") String phone, @JsonProperty("email") String email,
-            @JsonProperty("position") String position, @JsonProperty("department") String department,
-            @JsonProperty("address") String address, @JsonProperty("leave") String leave,
-            @JsonProperty("leaveLeft") String leaveLeft, @JsonProperty("tagged") List<JsonAdaptedTag> tagged,
-            @JsonProperty("leaveTaken") List<JsonAdaptedLeave> leaveTaken) {
+                             @JsonProperty("phone") String phone, @JsonProperty("email") String email,
```
Comment (kevinchangjk) [inline src/main/java/coydir/storage/JsonAdaptedPerson.java:49]: Wait is this just indentation? Why?

File: src/main/java/coydir/storage/JsonAdaptedPerson.java [hunk 2]
```diff
@@ -122,25 +123,29 @@ public Person toModelType() throws IllegalValueException {
         }
         final EmployeeId modelEmployeeId = new EmployeeId(employeeId);
 
-        if (phone == null) {
-            throw new IllegalValueException(String.format(MISSING_FIELD_MESSAGE_FORMAT, Phone.class.getSimpleName()));
+        final Phone modelPhone;
+        if (this.phone.equals("N/A")) {
+            modelPhone = new Phone();
+        } else {
```
Comment (kevinchangjk) [inline src/main/java/coydir/storage/JsonAdaptedPerson.java:129]: Can shorten it to an `else if` statement. Same for the rest.

File: src/main/java/coydir/storage/JsonAdaptedPerson.java [hunk 3]
```diff
@@ -149,24 +154,23 @@ public Person toModelType() throws IllegalValueException {
...
+            modelAddress = new Address();
+        } else {
+            if (!Address.isValidAddress(address)) {
+                throw new IllegalValueException(Address.MESSAGE_CONSTRAINTS);
+            }
+            modelAddress = new Address(address);
         }
-        final Address modelAddress = new Address(address);
 
-        if (leave == null) {
```
Comment (kevinchangjk) [inline src/main/java/coydir/storage/JsonAdaptedPerson.java:167]: Why remove this part?

File: src/test/java/coydir/storage/JsonAdaptedPersonTest.java [hunk 4]
```diff
@@ -93,15 +100,6 @@ public void toModelType_invalidPhone_throwsIllegalValueException() {
         assertThrows(IllegalValueException.class, expectedMessage, person::toModelType);
     }
 
-    @Test
-    public void toModelType_nullPhone_throwsIllegalValueException() {
```
Comment (kevinchangjk) [inline src/test/java/coydir/storage/JsonAdaptedPersonTest.java:97]: Wait why remove these test cases?

**Review by kevinchangjk — COMMENTED** [review]
LGTM, but got some questions for you, please clarify thanks.

File: src/main/java/coydir/storage/JsonAdaptedPerson.java (hunk 1 above)
Comment (prit3010) [reply src/main/java/coydir/storage/JsonAdaptedPerson.java:49]: Cause its exceeding the 120 char limit

File: src/main/java/coydir/storage/JsonAdaptedPerson.java (hunk 3 above)
Comment (prit3010) [reply src/main/java/coydir/storage/JsonAdaptedPerson.java:167]: Leave will never be null actually so its redundant

File: src/test/java/coydir/storage/JsonAdaptedPersonTest.java (hunk 4 above)
Comment (prit3010) [reply src/test/java/coydir/storage/JsonAdaptedPersonTest.java:97]: I am removing the null cases so I just had a overall test case encompass all the N/A cases

File: src/main/java/coydir/storage/JsonAdaptedPerson.java (hunk 3 above)
Comment (kevinchangjk) [reply src/main/java/coydir/storage/JsonAdaptedPerson.java:167]: This class (`JsonAdaptedPerson`) is meant for reading and writing JSON files, so it's not so simple. We shouldn't assume that the JSON files will be untampered.

image

If say the "leave" portion is changed to null, we can indeed get an error. So in line with defensive programming, it would be better to retain this.

File: src/test/java/coydir/storage/JsonAdaptedPersonTest.java (hunk 4 above)
Comment (kevinchangjk) [reply src/test/java/coydir/storage/JsonAdaptedPersonTest.java:97]: I think there's a bit of a mix-up here. `null` does not refer to "N/A". Those are two different values, and thus two different cases that deserve their own tests. Would it not be better to keep both?

File: src/main/java/coydir/storage/JsonAdaptedPerson.java (hunk 3 above)
Comment (prit3010) [reply src/main/java/coydir/storage/JsonAdaptedPerson.java:167]: Good point so we need to keep the null case for all of the fields?

Comment (kevinchangjk) [reply src/main/java/coydir/storage/JsonAdaptedPerson.java:167]: Yeah better to.

Comment (prit3010) [reply src/main/java/coydir/storage/JsonAdaptedPerson.java:167]: Added the Null Checks

**Review by kevinchangjk — APPROVED** [review]
LGTM.
