### PR TITLE
Fixed Rating bugs

### LINKED ISSUE #210: [PE-D][Tester D] Rating multiple times in a day results in a straight line graph
Perhaps a user should be prevented to rate multiple times in a day?

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: TheSoggy/ped#15

### PR DESCRIPTION
**Pull request by Kok-je**
Fixes #210 #200 #173 #120 

Fixed all rating related bugs:
- Fixed `rate` command exception message: "integer values of 1-5 inclusive" #173
- Implemented graph that displays **values beside each node** for clarity #200
- Fixed manipulation of json file that cause the graph to be inaccurate by implementing **sorting by date**
- Updated UG performance rating graph segment with **screen capture**
- Implemented "_Employee rating completed_" error when trying to rate employees more than once per day #210

image

### CODE REVIEW

**Review by chao890 — APPROVED** [review]

File: src/main/java/coydir/logic/commands/RateCommand.java [hunk 1]
```diff
@@ -59,6 +61,12 @@ public CommandResult execute(Model model) throws CommandException {
             throw new CommandException(Messages.MESSAGE_INVALID_PERSON_DISPLAYED_INDEX);
         }
 
+        for (Rating ratinglist : targetPerson.getRatingHistory()) {
+            if (ratinglist.getTime().equals(rating.getTime())) {
+                throw new CommandException(MESSAGE_EMPLOYEE_RATING_COMPLETED);
```
Comment (prit3010) [inline src/main/java/coydir/logic/commands/RateCommand.java:66]: Maybe something to think about (don't need to change). Given that you can only add one rating a day, your last rating in the list would be the only date that you might check against. Then you would not need a for loop. But since there is no time sensitivity, not super necessary

File: src/main/java/coydir/ui/PersonInfo.java [hunk 2]
```diff
@@ -149,8 +170,11 @@ public void updateIndex(int index) {
         for (int i = 0; i < person.getRatingHistory().size(); i++) {
             String timestamp = person.getRatingHistory().get(i).timestamp
                 .format(DateTimeFormatter.ofPattern("dd-MMM-yy"));
-            int value = Integer.parseInt(person.getRatingHistory().get(i).value);
-            series.getData().add(new XYChart.Data<String, Number>(timestamp, value));
+            Number value = Integer.parseInt(person.getRatingHistory().get(i).value);
+            var data = new XYChart.Data<String, Number>(timestamp, value);
+            System.out.println(data.YValueProperty());
```
Comment (prit3010) [inline src/main/java/coydir/ui/PersonInfo.java:175]: Hello.

**Review by prit3010 — CHANGES_REQUESTED** [review]
can remove print ln and think about the for loop thing

**Review by prit3010 — APPROVED** [review]
